To install apache on Woker machine

---
- name: Install httpd
  hosts: all
  become: true

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    tags: install_httpd

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
    tags: start_httpd

    - name: copy web content to /var/ww/html location
      copy:
        src: /home/controller/ansiblelab/all playbooks/index.html
        dest: /var/www/html/
    tags: copy_content


To delete apache on worker machine

---
- name: Remove Apache (httpd)
  hosts: all
  become: true

  tasks:
    - name: Stop httpd service
      service:
        name: httpd
        state: stopped
        enabled: no
    tags: stop_httpd

    - name: Remove httpd package
      yum:
        name: httpd
        state: absent
      tags: remove_httpd

    - name: Remove web content from /var/www/html
      file:
        path: /var/www/html/index.html
        state: absent
      tags: remove_content




Using Ad-hoc cmds            [-b] -> it is consider as superuser[root]
-----------------

To install
ansible all -m yum -a "name=httpd state=present" -b --tags install_httpd

To Start Service
ansible all -m service -a "name=httpd state=started enabled=true" -b --tags start_httpd

To Stop Service
ansible all -m service -a "name=httpd state=stopped enabled=true" -b --tags stop_httpd

To Remove
ansible all -m service -a "name=httpd state=stopped enabled=no" -b --tags stop_httpd
ansible all -m yum -a "name=httpd state=absent" -b --tags remove_httpd
