To install git

---
- name: Install git
  hosts: clients
  become: true

  tasks:
    - name: Install git
      yum:
        name: git
        state: present
    tags: install_git


To remove git & files

---
- name: remove git
  hosts: clients
  become: true

  tasks:
    - name: remove git
      yum:
        name: git
        state: absent
    tags: stop_git

    - name: remove git files
      command: yum autoremove -y
    tags: remove_git_files
