---
- name: Remove git
  hosts: clients
  become: true

  tasks:
    - name: Remove git package
      yum:
        name: git
        state: absent
      tags: stop_git

    - name: Remove unused dependencies (autoremove)
      yum:
        name: '*'
        state: absent
        autoremove: yes
      tags: remove_git_files
