---
- name: Install httpd
  hosts: all
  become: true

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy web content to /var/ww/html location
      copy:
        src: /home/controller/ansiblelab/all playbooks/index.html
        dest: /var/www/html/
